- hosts: fgt_a
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
  vdom: "root"
  ansible_connection: httpapi
  ansible_network_os: fortinet.fortios.fortios
  ansible_httpapi_use_ssl: yes
  ansible_httpapi_validate_certs: no
  ansible_httpapi_port: 443
  classification: "protected"
  default_login_banner: >
    This is a private computer system. Unauthorized access or use
    is prohibited and subject to prosecution and/or disciplinary
    action. Any use of this system constitutes consent to
    monitoring at all times and users are not entitled to any
    expectation of privacy. If monitoring reveals possible evidence
    of violation of criminal statutes, this evidence and any other
    related information, including identification information about
    the user, may be provided to law enforcement officials.
    If monitoring reveals violations of security regulations or
    unauthorized use, employees who violate security regulations or
    make unauthorized use of this system are subject to appropriate
    disciplinary action.

  tasks:
    - name: "Show Vars"
      debug: 
        msg: "{{ vars }}"

    - name: "Get Interface Status"
      register: interfaces
      fortios_monitor_fact:
        access_token: "{{ fortios_access_token }}" 
        selector: "system_available-interfaces"

    - name: "ISM-0428: Screen Lock"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          admin_console_timeout: 15

    - name: "ISM-0408: Login Banner"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          pre_login_banner: enable
          pre-login-banner-message: "{{ login_banner | default(default_login_banner) }}"

    - name: "ISM-0421: Password Policy (Protected)"
      when: classification == "protected"
      fortios_system_password_policy:
        access_token: "{{ fortios_access_token }}" 
        system_password_policy:
          apply_to: admin-password
          min_lower_case_letter: 1
          min_upper_case_letter: 1
          min_non_alphanumeric: 1
          minimum_length: 14
          min_number: 1
          min_change_characters: 1
          reuse_password: disable
          status: enable

    - name: "ISM-1557: Password Policy (Secret)"
      when: classification == "secret"
      fortios_system_password_policy:
        access_token: "{{ fortios_access_token }}" 
        system_password_policy:
          apply_to: admin-password
          min_lower_case_letter: 1
          min_upper_case_letter: 1
          min_non_alphanumeric: 1
          minimum_length: 17
          min_number: 1
          min_change_characters: 1
          reuse_password: disable
          status: enable

    - name: "ISM-0433: Password Policy (Top Secret)"
      when: classification == "top_secret"
      fortios_system_password_policy:
        access_token: "{{ fortios_access_token }}" 
        system_password_policy:
          apply_to: admin-password
          min_lower_case_letter: 1
          min_upper_case_letter: 1
          min_non_alphanumeric: 1
          minimum_length: 20
          min_number: 1
          min_change_characters: 1
          reuse_password: disable
          status: enable

    - name: "ISM-1403: Failed Login Account Lockout"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          admin_lockout_threshold: 5
          admin_lockout_duration: 300

    - name: "ISM-1590: Password Expiry"
      fortios_system_password_policy:
        access_token: "{{ fortios_access_token }}" 
        system_password_policy:
          expire_status: enable
          expire_day: 365
      

    - name: "ISM-0521: IPv6 Disable"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          gui_ipv6: disable
          ipv6_allow_anycast_probe: disable
          ipv6_allow_traffic_redirect: disable


    - name: "ISM-1304: Default Account Disable"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          admin_maintainer: disable 

    - name: "ISM_0534: Disable Unused Ports"
      loop:
        "{{ interfaces.meta.results | selectattr('is_physical', 'true') | selectattr('link', 'equalto', 'down') | list }}"
      fortios_system_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface:
          name: "{{ item.name }}"
          status: "down"

    - name: "ISM-1311: Disable SNMP v1 and v2"
      fortios_system_snmp_sysinfo:
        system_snmp_sysinfo:
          status: disable

    - name: "ISM-0471: ASD Approved Cryptographic Algorithms"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          strong_crypto: enable

    - name: "ISM-0994: Prefer ECDH and ECDSA"
      meta: noop

    - name: "ISM-0472: Use DH Modulus of at least 2048 Bits"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          dh_params: "8192"

    - name: "ISM-1139: Use latest TLS version"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          admin_https_ssl_versions: "tlsv1-3"
          ssl_min_proto_version: "tlsv1-3"

    - name: "ISM-1453: PFS is used for TLS connections"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          ssl_static_key_ciphers: disable

    - name: "ISM-1506: The use of SSH version 1 is disabled."
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          admin_ssh_v1: disable
          admin_telnet: disable

    - name: "ISM-0484: SSH daemon configuration"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          ssh_hmac_md5: disable
          ssh_cbc_cipher: disable

    - name: "ISM_0484: SSH daemon configuration"
      fortios_system_global:
        access_token: "{{ fortios_access_token }}" 
        system_global:
          ssh_hmac_md5: disable
          ssh_cbc_cipher: disable
